batch_size: 20
dataset_path: dataset
device: cuda
epochs: 100
img_size: 640
lr: 0.0025
max_samples: 500
model_size: yolo11s
num_classes: 7
output_dir: runs/train
pseudo_conf: 0.35
weight_decay: 2.0e-05
